#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

fast=${fast:-} # optimization

df=${df:-d.json}
dp=$(ruby -e 'puts File.absolute_path(ARGV[0])' "$df")
be=${be:-echo}

export dp be

[[ $fast ]] || {
  # setup app state
  mkdir -p share
  mkdir -p chunks
  [[ -f d.json ]] || echo "{}" > d.json
}

# setup gui
[[ $fast ]] || (
  cd gui
  mkdir -p tmp
  [[ -f tmp/main-window-state.json ]] ||
    echo "{}" > tmp/main-window-state.json
  npm install
)

# start backend in background
$be peer &
gui/node_modules/.bin/electron gui
# when frontend exits, exit here, this will reap backend
exit
